[project]
name = "tutor_flow"
version = "0.1.0"
description = "tutor-flow using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.11.1"
]

[project.scripts]
kickoff = "tutor_flow.main:kickoff"
run_crew = "tutor_flow.main:kickoff"
plot = "tutor_flow.main:plot"
run_with_trigger = "tutor_flow.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "flow"
